Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
      - !Ref InstanceSecurityGroup
      NetworkInterfaces:
        - SubnetId: subnet-0491d85b30e0a35d0
      KeyName: udacity
      ImageId: 'ami-0a634ae95e11c6f91' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: vpc-0b9b7a5c95ae59eff
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
