Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      NetworkInterfaces:
        - SubnetId: subnet-0491d85b30e0a35d0
          DeviceIndex: "0"
          GroupSet:
          - Ref: InstanceSecurityGroup
      KeyName: udacity
      ImageId: 'ami-0a634ae95e11c6f91'
      InstanceType: t2.medium
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: vpc-0b9b7a5c95ae59eff
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
